### ISSUE TITLE
duplicate package

### ISSUE THREAD

**Issue by jasonkarns** [bibliolabs/docCookies#1]
I incidentally created a duplicate package (https://github.com/jasonkarns/doc-cookies)

It appears we both took the package from MDN. I wouldn't mind killing my repo, if you'd be open to a few PRs.

I would:
1. update the code to reflect the latest from MDN
2. add the readme (taken from MDN)
3. clean up package.json (wrong version, noop test script, unnecessarily verbose dist script, add main)
4. remove the dist from git (only needs to be in npm, via prepublish)
5. swap umd for browserify so that the `main` script can be plain commonjs, letting the built bundle be umd. (let's the module be requireable via node/browserify without the umd cruft)

Thoughts?

**Comment by jasonkarns** [comment]
ping

**Comment by evanmuller** [comment]
Sorry for the late response on this. This repo started out as a fork of: https://gist.github.com/jonmagic/9521363, which is all I could find when looking for that MDN code in github.

I'm open to PRs for 1-4, not sure about 5.  I don't want the module system to be part of the source if this is what you mean.

Thanks for reaching out to consolidate these repos.

**Comment by jasonkarns** [comment]
I actually switched my module from browserify to umd, so # 5 is moot. Though I do still prefer the module to be commonjs by default, and letting umd provide the wrappers for amd/global. but i'll open the PRs for these and we'll see where it goes.

**Comment by jasonkarns** [comment]
#2 for item 2 above
#3 for items 3 and 4 above
