### ISSUE TITLE
Update to revision #3

### ISSUE THREAD

**Issue by kirly-af** [bibliolabs/docCookies#7]
It seems revision 3 has been released here: https://github.com/madmurphy/cookies.js
What do you think about updating it ?

**Comment by evanmuller** [comment]
Thanks for pointing this out. I'm all for updating, just give me a chance to look at the diff, or, if you want, submit a PR.

Looks like the original code is here: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie/Simple_document.cookie_framework

**Comment by kirly-af** [comment]
Hi @evanmuller,
Well, @madmurphy seems to be the original author. That repo is already a node package btw, it's just not published yet (I'm actually using his version in production). There's an issue about publishing that module: https://github.com/madmurphy/cookies.js/issues/10

As that repo is from the original author and main maintainer, what do you think of simply replacing the published module with a fork?

**Comment by kirly-af** [comment]
Well, actually I think the ideal way would be that you publish directly from madmurphy's repo, what's your opinion?

**Comment by kirly-af** [comment]
I created https://github.com/madmurphy/cookies.js/pull/11, I think that's the best way to go as the other repo seems to be more active.

**Comment by evanmuller** [comment]
Thanks @kirly-af I did exactly what you suggested and published @madmurphy's repo to doc-cookies npm.

**Comment by kirly-af** [comment]
@evanmuller 
Awesome! Thanks for being so reactive !
